### PR TITLE
feat: rename folders and remove hidden files button

### PR DESCRIPTION
**Pull request by johnvente**
### Description

This allows you to rename a folder in the tree of directories and remove the 'hidden files' from the toolbar.

ezgif com-video-to-gif (3)

#### "Show hidden files" button

Before           |  Now
:-------------------------:|:-------------------------:
  |  

### How to test it

- Check this branch`jv/fix-chonky-improvements` in the XBlock files manager

1. use node 18
 ```
nvm use
```

2. install dependencies
```
yarn install 
```
3 run to see any change in the react code 
```
yarn dev 
```
------------------------------------------------------------------------------------------------------------------------------------------------
Now select a folder to rename (click in the folder) -> "Rename folder"

rename-folder

You will see a prompt to change the name of the folder

rename-prompt

To check **"Show hidden files"** button, you would need to click **"Options"** button

optiones-button

**Merge checklist:**
Check off if complete *or* not applicable:
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Fixup commits are squashed away
- [ ] Unit tests added/updated
- [ ] Manual testing instructions provided
- [ ] Noted any: Concerns, dependencies, migration issues, deadlines, tickets

### CODE REVIEW

**Review by Ian2012 — APPROVED** [review]

**Comment by Ian2012** [comment]
@johnvente There is a small delay in updating the list of actions when selecting folders. Can you try to speed that up?

I think you can avoid using the spread operator here twice:

https://github.com/eduNEXT/xblock-filesmanager/pull/25/files#diff-c7b3d6d48f9ac68ace728b78de9dfa0c587a909e09f13e4edf38ce0b1c07f1b3R68-R69

**Comment by BryanttV** [comment]
Hi @johnvente, Everything works fine! As a suggestion, I think the `Rename folder` action should be followed by `Delete folders` from the list of actions.

Question: Will the action of opening a preview be implemented in this PR?

**Comment by johnvente** [comment]
> @johnvente There is a small delay in updating the list of actions when selecting folders. Can you try to speed that up?
> 
> I think you can avoid using the spread operator here twice:
> 
> https://github.com/eduNEXT/xblock-filesmanager/pull/25/files#diff-c7b3d6d48f9ac68ace728b78de9dfa0c587a909e09f13e4edf38ce0b1c07f1b3R68-R69
> 
> It's only happening the first time you open it.


Hi @Ian2012 I've changed the speed for the actions for selecting folders and a refactor of the spread operator

**Comment by johnvente** [comment]
> Hi @johnvente, Everything works fine! As a suggestion, I think the `Rename folder` action should be followed by `Delete folders` from the list of actions.
> 
> Question: Will the action of opening a preview be implemented in this PR?

I've done the change for those positions, for opening a preview you can check it out now

new-rename-folder

**Review by mariajgrimaldi — APPROVED** [review]

**Pull request merged**
